language: elixir

sudo: false

elixir:
  - 1.4
  - 1.5
  - 1.6
  - 1.7

otp_release:
  - 19.3
  - 20.0
  - 21.0

env: MIX_ENV=test

script:
  - mix coveralls.travis
  - mix credo --strict

notifications:
  email: false
