language: elixir

sudo: false

cache:
  directories:
    - _build
    - deps

elixir:
  - 1.4
  - 1.5
  - 1.6
  - 1.7

otp_release:
  - 19.3
  - 20.0
  - 21.0

matrix:
  exclude:
    - elixir: 1.4
      otp_release: 21.0
    - elixir: 1.5
      otp_release: 21.0

env: MIX_ENV=test

script:
  - mix coveralls.travis
  - mix credo --strict

notifications:
  email: false
